name: "Nova issue  - padrão"
description: "Use este formulário para abrir issues seguindo nosso padrão."
title: "Breve resumo da demanda"
labels: [ ]

body:
  - type: textarea
    id: conteudo
    attributes:
      label: Detalhamento da Demanda
      description: Preencha as seções abaixo conforme o tipo da issue.
      value: |
        ### **Descrição**
        
        ---

        ### **Regras de negócio**
        
        ---

        ### **Critérios de aceite**
        - [ ] Critério 1

        ---

        ### **Passos para reprodução**
        1. Passo 1

        ---

        ### **Anexos**

    validations:
      required: true
