name: "Nova issue - padrão"
description: "Use este formulário para abrir issues seguindo nosso padrão."

body:
  - type: textarea
    id: conteudo
    attributes:
      label: ""  # mantém o campo renderizado sem exibir título
      value: |
        ### **Descrição**
        
        ---

        ### **Regras de negócio**
        
        ---

        ### **Critérios de aceite**
        - [ ] Critério 1

        ---

        ### **Passos para reprodução**
        1. Passo 1

        ---

        ### **Anexos**
    validations:
      required: true
