name: "🧪 Teste (mínimo)"
description: "Template mínimo para validar Issue Forms."
title: "[Teste] "
body:
  - type: input
    id: resumo
    attributes:
      label: Resumo
      description: Escreva um resumo em uma frase.
    validations:
      required: true
