name: Maven Build

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      maven-args:
        required: false
        type: string
        default: '-B package --file pom.xml'
    # Declara os secrets que o workflow precisa
    secrets:
      GH_APP_ID:
        required: true
      GH_APP_PRIVATE_KEY:
        required: true

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Gerar token do GitHub App
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven
          server-id: github
          server-username: x-access-token
          server-password: GH_APP_GENERATED_TOKEN
          settings-path: ${{ github.workspace }}

      - name: Build com Maven
        run: mvn -s $GITHUB_WORKSPACE/settings.xml ${{ inputs.maven-args }}
        env:
          GH_APP_GENERATED_TOKEN: ${{ steps.app-token.outputs.token }}