name: Maven Deploy

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      module-path:
        required: true
        type: string
        description: 'Caminho relativo do módulo a publicar'
      maven-args:
        required: false
        type: string
        default: 'deploy -DskipTests -B'
    secrets:
      CICD_MAVEN_PAT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven
          server-id: github
          server-username: fabriciobs # Seu usuário fixado
          server-password: MAVEN_PAT
          settings-path: ${{ github.workspace }}

      - name: Deploy com Maven
        run: mvn -s $GITHUB_WORKSPACE/settings.xml ${{ inputs.maven-args }}
        working-directory: ${{ inputs.module-path }}
        env:
          MAVEN_PAT: ${{ secrets.CICD_MAVEN_PAT }}