name: Maven Build

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      maven-args:
        required: false
        type: string
        default: '-B package --file pom.xml'

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven
          server-id: github-cpb-libs
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          settings-path: ${{ github.workspace }}

      - name: Build com Maven
        run: mvn -s $GITHUB_WORKSPACE/settings.xml ${{ inputs.maven-args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}